export const mussoGrandModels = [
  {
    name: "Platinum D2.2 4x2",
    slug: "musso_grand_platinum_d22_4x2",
    image: require("./kgm-uygulama-dosyalar/gorsel/musso_grand4.png"),
    desc_item: ["Otomatik", "Dizel", "4x2"],
    desc: "₺1.498.894'den başlayan fiyatlarla",
    technic_properties: [
      {
        name: "Genel Bakış",
        props: [
          {
            name: "Kapı Sayısı",
            value: "4 Kapı",
          },
          {
            name: "Azami Sürat",
            value: "172 km/saat",
          },
          {
            name: "Silindir Sayısı",
            value: "4 Silindir",
          },
          {
            name: "Vites Sayısı",
            value: "6 Vites",
          },
        ],
      },
      {
        name: "Motor ve Performans",
        props: [
          {
            name: "Motor Gücü",
            value: "202 HP",
          },
          {
            name: "Motor Hacmi",
            value: "2157 cc",
          },
          {
            name: "Maksimum Tork",
            value: "441 Nm (1600-2600 d/dk) Nm",
          },
          {
            name: "Maksimum Devir",
            value: "3800 rpm",
          },
        ],
      },
      {
        name: "Yakıt Tüketimi",
        props: [
          {
            name: "Ortalama Yakıt Tüketimi",
            value: "9.0 L",
          },
          {
            name: "Yakıt Deposu",
            value: "75 L",
          },
        ],
      },
      {
        name: "Boyutlar",
        props: [
          {
            name: "Koltuk Sayısı",
            value: "5 Koltuk",
          },
          {
            name: "Uzunluk",
            value: "5405 mm",
          },
          {
            name: "Genişlik",
            value: "1950 mm",
          },
          {
            name: "Yükseklik",
            value: "1885 mm",
          },
          {
            name: "Net Ağırlık",
            value: "2095 kg",
          },
          {
            name: "Bagaj Hacmi",
            value: "1441 lt",
          },
          {
            name: "Lastik Ölçüleri",
            value: "255/70 R17 - 255/60 R18 - 255/50 R20",
          },
        ],
      },
    ],
    hardware_properties: [
      {
        name: "Güvenlik",
        props: [
          "ARP (Aktif Devrilme Önleyici)",
          "HSA (Yokuş Kalkış Sistemi)",
          "HDC (Yokuş İniş Kontrolü)",
          "TPMS (Lastik Basıncı İzleme Sistemi)",
          "Hıza Duyarlı Emniyet Kemeri Uyarısı",
          "HBA (Uzun Far Asistanı)",
          "Alarm",
          "ESS (Acil Durum Arka Sinyal Sistemi)",
          "ESP (Elektronik Stabilite Programı)",
          "ABS (Kilitlenme Karşıtı Fren Sistemi)",
          "TCS (Çekiş Kontrol Sistemi)",
          "HBA (Hidrolik Fren Asistanı)",
          "Immobilizer",
          "Sürücü ve Yolcu Ön Hava Yastıkları",
          "Önde Hava Soğutmalı Disk Frenler",
          "Arkada Disk Frenler",
          "Yükseklik Ayarlı Ön Emniyet Kemerleri",
          "Yüksek Mukavemetli Çelik Şasi",
          "Ultra Sert 4 Katmanlı Şasi Yapısı",
          "Yan Çarpmalardan Optimum Koruma Sağlayan Kapı Çarpışma Kirişleri",
          "EBD- Elektronik Fren Dağıtım Sistemi",
          "Hıza Duyarlı Kapı Kilidi",
          "Isofıx Çocuk Koltuğu Bağlantısı",
          "İlk Yardım Kiti",
        ],
      },
      {
        name: "Multimedia",
        props: [
          'Akıllı Ses Sistemi 8" (Geri Görüş Kamerası ve Akıllı Telefon bağlantılı)',
          "Araç Bağlantısı (Apple Carplay/Google Android Auto)",
          "6 Adet Hoparlör",
          "Müzik Sistemi- DAB",
          "Bluetooth Bağlantı",
          "USB Bağlantısı",
        ],
      },
      {
        name: "Konfor",
        props: [
          "Otomatik Far Kontrolü ve Otomatik Silecek Kontrolü",
          "Helezon Yaylı 5 Nokta Bağlantılı Arka Süspansiyon",
          "6 Yönlü Ayarlanabilir Sürücü ve Yolcu Ön Koltuğu",
          "2.Sıra Koltukların Katlanması İçin Katlanır Dirseklik",
          "Öne Kaymalı Ön Koltuk Başlıkları",
          "Otomatik Buğu Çözme",
          "Cruise Control (Hız Sabitleme Sistemi)",
          "Elektrikli Direksiyon Kolonu Kilidi",
          "Kumaş Koltuk Döşeme",
          "Lastik Tamir Kiti",
          "Hıza Duyarlı Hidrolik Direksiyon",
          "B Direğinde Tutma Kolu",
          "Tuş Kilitli Torpido Kutusu",
          "Yükseklik Ayarlı Ön Koltuk Başlıkları",
          "60/40 Katlanabilir ve Yatırılabilir Arka Koltuklar",
          "Katlanır Kol Dayama",
          "Yükseklik Ayarlı Sürücü Koltuğu",
          "Işıklı Makyaj Aynası",
          "Yükleme Alanında Alet Kutusu",
          "Bagaj Kasa Kancaları",
          "Akıllı Anahtar",
          "Helezon Yaylı Çift Salıncaklı Ön Süspansiyon",
        ],
      },
      {
        name: "Dış Donanım",
        props: [
          "Arka Sis Farları",
          "Far Yükseklik Ayarı",
          "Hafif ve Güçlendirilmiş Arka Bagaj Kapağı",
          '17" Aluminyum Alaşım Jant',
          "Aerodinamik Dış Dikiz Aynaları",
          "Aerodinamik Silecek Kolları",
          "Gövde Rengi Kapı Kolları ve Gizli Anahtar Deliği",
          "Köpekbalığı Anten",
          "Ön Sis Farları",
          "Siyah Hava Giriş Izgarası",
          "Gövde Rengi Kapı Kolları",
          "Elektrikli Güvenlikli Sürücü Camı",
          "Gümüş Şık Tavan Çıtaları",
          "Mercekli Projeksiyon Tipi Farlar",
          "Isıtmalı Ön Cam",
          "Renkli Yan Camlar",
          "Ses Yalıtımlı Renkli Ön Cam",
          "Sesi Azaltan Akustik Motor Kapağı",
          "LED Arka Stop",
          "Görsel VIN (Şasi Numarası)",
          "Temiz Tutan Kapı Eşikleri",
        ],
      },
      {
        name: "İç Donanım",
        props: [
          "Derinlik ve Yükseklik Ayarlı Teleskopik Direksiyon",
          "Elektrikli Ön Camlar",
          "Elektrikli Arka Camlar",
          "Tek Dokunmalı Üçlü Sinyal",
          "Gümüş İç Kapı Kolları",
          "Otomatik Kararan Iç Dikiz Aynası",
          "12V Güç Soketi",
        ],
      },
      {
        name: "Bilgi Sistemi",
        props: [
          'Yol Bilgisayarı (3.5" Mono TFT-LCD Ekran)',
          "Direksiyondan Kumanda Sistemi",
        ],
      },
    ],
  },
  {
    name: "Platinum Plus D2.2 4x2",
    slug: "musso_grand_platinum_plus_d22_4x2",
    image: require("./kgm-uygulama-dosyalar/gorsel/musso_grand3.png"),
    desc_item: ["Otomatik", "Dizel", "4x2"],
    desc: "₺1.618.894'den başlayan fiyatlarla",
    technic_properties: [
      {
        name: "Genel Bakış",
        props: [
          {
            name: "Kapı Sayısı",
            value: "4 Kapı",
          },
          {
            name: "Azami Sürat",
            value: "172 km/saat",
          },
          {
            name: "Silindir Sayısı",
            value: "4 Silindir",
          },
          {
            name: "Vites Sayısı",
            value: "6 Vites",
          },
        ],
      },
      {
        name: "Motor ve Performans",
        props: [
          {
            name: "Motor Gücü",
            value: "202 HP",
          },
          {
            name: "Motor Hacmi",
            value: "2157 cc",
          },
          {
            name: "Maksimum Tork",
            value: "441 Nm (1600-2600 d/dk) Nm",
          },
          {
            name: "Maksimum Devir",
            value: "3800 rpm",
          },
        ],
      },
      {
        name: "Yakıt Tüketimi",
        props: [
          {
            name: "Ortalama Yakıt Tüketimi",
            value: "9.0 L",
          },
          {
            name: "Yakıt Deposu",
            value: "75 L",
          },
        ],
      },
      {
        name: "Boyutlar",
        props: [
          {
            name: "Koltuk Sayısı",
            value: "5 Koltuk",
          },
          {
            name: "Uzunluk",
            value: "5405 mm",
          },
          {
            name: "Genişlik",
            value: "1950 mm",
          },
          {
            name: "Yükseklik",
            value: "1885 mm",
          },
          {
            name: "Net Ağırlık",
            value: "2095 kg",
          },
          {
            name: "Bagaj Hacmi",
            value: "1441 lt",
          },
          {
            name: "Lastik Ölçüleri",
            value: "255/70 R17 - 255/60 R18 - 255/50 R20",
          },
        ],
      },
    ],
    hardware_properties: [
      {
        name: "Güvenlik",
        props: [
          "ARP (Aktif Devrilme Önleyici)",
          "HSA (Yokuş Kalkış Sistemi)",
          "HDC (Yokuş İniş Kontrolü)",
          "TPMS (Lastik Basıncı İzleme Sistemi)",
          "Hıza Duyarlı Emniyet Kemeri Uyarısı",
          "HBA (Uzun Far Asistanı)",
          "AEBS (Bağımsız Acil Fren Sistemi)",
          "Alarm",
          "ESS (Acil Durum Arka Sinyal Sistemi)",
          "ESP (Elektronik Stabilite Programı)",
          "ABS (Kilitlenme Karşıtı Fren Sistemi)",
          "TCS (Çekiş Kontrol Sistemi)",
          "HBA (Hidrolik Fren Asistanı)",
          "Immobilizer",
          "Sürücü ve Yolcu Ön Hava Yastıkları",
          "Önde Hava Soğutmalı Disk Frenler",
          "Arkada Disk Frenler",
          "Yükseklik Ayarlı Ön Emniyet Kemerleri",
          "Ultra Sert 4 Katmanlı Şasi Yapısı",
          "Yan Çarpmalardan Optimum Koruma Sağlayan Kapı Çarpışma Kirişleri",
          "EBD- Elektronik Fren Dağıtım Sistemi",
          "Hıza Duyarlı Kapı Kilidi",
          "Isofıx Çocuk Koltuğu Bağlantısı",
          "İlk Yardım Kiti",
          "Hızı Algılayan Otomatik Kapı Kilitleri	",
        ],
      },
      {
        name: "Multimedia",
        props: [
          'Akıllı Ses Sistemi 8" (Geri Görüş Kamerası ve Akıllı Telefon bağlantılı)',
          "Araç Bağlantısı (Apple Carplay/Google Android Auto)",
          "6 Adet Hoparlör",
          "Müzik Sistemi- DAB",
          "Bluetooth Bağlantı",
          "USB Bağlantısı",
        ],
      },
      {
        name: "Konfor",
        props: [
          "Otomatik Far Kontrolü ve Otomatik Silecek Kontrolü",
          "Helezon Yaylı 5 Nokta Bağlantılı Arka Süspansiyon",
          "Öne Kaymalı Ön Koltuk Başlıkları",
          "Otomatik Buğu Çözme",
          "Cruise Control (Hız Sabitleme Sistemi)",
          "Elektrikli Direksiyon Kolonu Kilidi",
          "Lastik Tamir Kiti",
          "Hıza Duyarlı Hidrolik Direksiyon",
          "B Direğinde Tutma Kolu",
          "Tuş Kilitli Torpido Kutusu",
          "Yükseklik Ayarlı Ön Koltuk Başlıkları",
          "60/40 Katlanabilir ve Yatırılabilir Arka Koltuklar",
          "Katlanır Kol Dayama",
          "Yükseklik Ayarlı Sürücü Koltuğu",
          "Işıklı Makyaj Aynası",
          "Yükleme Alanında Alet Kutusu",
          "Bagaj Kasa Kancaları",
          "Akıllı Anahtar",
          "Helezon Yaylı Çift Salıncaklı Ön Süspansiyon",
          "Elektrikli Ön Koltuklar	",
          "Isıtmalı Ön Koltuklar	",
          "Isıtmalı Arka Koltuklar	",
        ],
      },
      {
        name: "Dış Donanım",
        props: [
          "Arka Sis Farları",
          "Far Yükseklik Ayarı",
          "Hafif ve Güçlendirilmiş Arka Bagaj Kapağı",
          "Aerodinamik Dış Dikiz Aynaları",
          "Aerodinamik Silecek Kolları",
          "Gövde Rengi Kapı Kolları ve Gizli Anahtar Deliği",
          "Köpekbalığı Anten",
          "Ön Sis Farları",
          "Siyah Hava Giriş Izgarası",
          "Gövde Rengi Kapı Kolları",
          "Elektrikli Güvenlikli Sürücü Camı",
          "Gümüş Şık Tavan Çıtaları",
          "Mercekli Projeksiyon Tipi Farlar",
          "Isıtmalı Ön Cam",
          "Renkli Yan Camlar",
          "Ses Yalıtımlı Renkli Ön Cam",
          "Sesi Azaltan Akustik Motor Kapağı",
          "LED Arka Stop",
          "Görsel VIN (Şasi Numarası)",
          "Temiz Tutan Kapı Eşikleri",
          "Aralıklı Arka Cam Sileceği",
          "Ön Kapı Aydınlatma Lambası",
          '18" Alüminyum Alaşım Jant',
        ],
      },
      {
        name: "İç Donanım",
        props: [
          "Derinlik ve Yükseklik Ayarlı Teleskopik Direksiyon",
          "Elektrikli Ön Camlar",
          "Elektrikli Arka Camlar",
          "Tek Dokunmalı Üçlü Sinyal",
          "Gümüş İç Kapı Kolları",
          "Otomatik Kararan Iç Dikiz Aynası",
          "12V Güç Soketi",
          "Deri Kaplama Koltuklar",
          "Deri Kaplama Direksiyon",
        ],
      },
      {
        name: "Bilgi Sistemi",
        props: [
          'Yol Bilgisayarı (3.5" Mono TFT-LCD Ekran)',
          "Direksiyondan Kumanda Sistemi",
        ],
      },
    ],
  },
  {
    name: "Platinum Plus D2.2 4x4",
    slug: "musso_grand_platinum_plus_d22_4x4",
    image: require("./kgm-uygulama-dosyalar/gorsel/musso_grand7.png"),
    desc_item: ["Otomatik", "Dizel", "4x4"],
    desc: "₺1.824.165'den başlayan fiyatlarla",
    technic_properties: [
      {
        name: "Genel Bakış",
        props: [
          {
            name: "Kapı Sayısı",
            value: "4 Kapı",
          },
          {
            name: "Azami Sürat",
            value: "172 km/saat",
          },
          {
            name: "Silindir Sayısı",
            value: "4 Silindir",
          },
          {
            name: "Vites Sayısı",
            value: "6 Vites",
          },
        ],
      },
      {
        name: "Motor ve Performans",
        props: [
          {
            name: "Motor Gücü",
            value: "202 HP",
          },
          {
            name: "Motor Hacmi",
            value: "2157 cc",
          },
          {
            name: "Maksimum Tork",
            value: "441 Nm (1600-2600 d/dk) Nm",
          },
          {
            name: "Maksimum Devir",
            value: "3800 rpm",
          },
        ],
      },
      {
        name: "Yakıt Tüketimi",
        props: [
          {
            name: "Ortalama Yakıt Tüketimi",
            value: "9.2 L",
          },
          {
            name: "Yakıt Deposu",
            value: "75 L",
          },
        ],
      },
      {
        name: "Boyutlar",
        props: [
          {
            name: "Koltuk Sayısı",
            value: "5 Koltuk",
          },
          {
            name: "Uzunluk",
            value: "5405 mm",
          },
          {
            name: "Genişlik",
            value: "1950 mm",
          },
          {
            name: "Yükseklik",
            value: "1885 mm",
          },
          {
            name: "Net Ağırlık",
            value: "2195 kg",
          },
          {
            name: "Bagaj Hacmi",
            value: "1441 lt",
          },
          {
            name: "Lastik Ölçüleri",
            value: "255/70 R17 - 255/60 R18 - 255/50 R20",
          },
        ],
      },
    ],
    hardware_properties: [
      {
        name: "Güvenlik",
        props: [
          "ARP (Aktif Devrilme Önleyici)",
          "HSA (Yokuş Kalkış Sistemi)",
          "HDC (Yokuş İniş Kontrolü)",
          "TPMS (Lastik Basıncı İzleme Sistemi)",
          "Hıza Duyarlı Emniyet Kemeri Uyarısı",
          "HBA (Uzun Far Asistanı)",
          "AEBS (Bağımsız Acil Fren Sistemi)",
          "Alarm",
          "ESS (Acil Durum Arka Sinyal Sistemi)",
          "ESP (Elektronik Stabilite Programı)",
          "ABS (Kilitlenme Karşıtı Fren Sistemi)",
          "TCS (Çekiş Kontrol Sistemi)",
          "HBA (Hidrolik Fren Asistanı)",
          "Immobilizer",
          "Sürücü ve Yolcu Ön Hava Yastıkları",
          "Önde Hava Soğutmalı Disk Frenler",
          "Arkada Disk Frenler",
          "Yükseklik Ayarlı Ön Emniyet Kemerleri",
          "Ultra Sert 4 Katmanlı Şasi Yapısı",
          "Yan Çarpmalardan Optimum Koruma Sağlayan Kapı Çarpışma Kirişleri",
          "EBD- Elektronik Fren Dağıtım Sistemi",
          "Hıza Duyarlı Kapı Kilidi",
          "Isofıx Çocuk Koltuğu Bağlantısı",
          "İlk Yardım Kiti",
          "Hızı Algılayan Otomatik Kapı Kilitleri	",
          "Ön Emniyet Kemeri Yük Sınırlama Düzeneği ve Kilitleme Dilli Ön Gergiler",
          "Acil Arama Sistemi",
          "Takviyeli Monoblok Gövde Yapısı",
          "Yan Darbelere Karşı Kapı Darbe Kirişleri",
          "Ön Yolcu Hava Yastığı Kapama Düğmesi",
        ],
      },
      {
        name: "Multimedia",
        props: [
          'Akıllı Ses Sistemi 8" (Geri Görüş Kamerası ve Akıllı Telefon bağlantılı)',
          "Araç Bağlantısı (Apple Carplay/Google Android Auto)",
          "6 Adet Hoparlör",
          "Müzik Sistemi- DAB",
          "Bluetooth Bağlantı",
          "USB Bağlantısı",
          "AUX Girişi",
        ],
      },
      {
        name: "Konfor",
        props: [
          "Helezon Yaylı 5 Nokta Bağlantılı Arka Süspansiyon",
          "Öne Kaymalı Ön Koltuk Başlıkları",
          "Otomatik Buğu Çözme",
          "Cruise Control (Hız Sabitleme Sistemi)",
          "Elektrikli Direksiyon Kolonu Kilidi",
          "Lastik Tamir Kiti",
          "B Direğinde Tutma Kolu",
          "Tuş Kilitli Torpido Kutusu",
          "Yükseklik Ayarlı Ön Koltuk Başlıkları",
          "60/40 Katlanabilir ve Yatırılabilir Arka Koltuklar",
          "Katlanır Kol Dayama",
          "Yükseklik Ayarlı Sürücü Koltuğu",
          "Işıklı Makyaj Aynası",
          "Yükleme Alanında Alet Kutusu",
          "Helezon Yaylı Çift Salıncaklı Ön Süspansiyon",
          "Elektrikli Ön Koltuklar	",
          "Isıtmalı Ön Koltuklar	",
          "Isıtmalı Arka Koltuklar	",
          "EPS (Elektrik Destekli Direksiyon)",
          "Elektronik Park Freni (Otomatik Tutmalı)",
          "Sürüş Modları Sistemi (Normal/Kış/Spor)",
          "Smart Key (Akıllı Anahtar-Anahtarsız Giriş/Çalıştırma/Kilitleme)",
          "Kablosuz Şarj",
          "Stop and Go Sistemi (ISG)",
          "4x4 Geçiş Düğmesi ( 2H,4H,4L)",
        ],
      },
      {
        name: "Dış Donanım",
        props: [
          "Arka Sis Farları",
          "Far Yükseklik Ayarı",
          "Hafif ve Güçlendirilmiş Arka Bagaj Kapağı",
          "Aerodinamik Dış Dikiz Aynaları",
          "Ön Sis Farları",
          "Siyah Hava Giriş Izgarası",
          "Gövde Rengi Kapı Kolları",
          "Elektrikli Güvenlikli Sürücü Camı",
          "Gümüş Şık Tavan Çıtaları",
          "Mercekli Projeksiyon Tipi Farlar",
          "Isıtmalı Ön Cam",
          "Renkli Yan Camlar",
          "Ses Yalıtımlı Renkli Ön Cam",
          "Sesi Azaltan Akustik Motor Kapağı",
          "LED Arka Stop",
          "LED Kapı İçi Aydınlatma",
          "Görsel VIN (Şasi Numarası)",
          "Temiz Tutan Kapı Eşikleri",
          "Aralıklı Arka Cam Sileceği",
          "Ön Kapı Aydınlatma Lambası",
          '18" Alüminyum Alaşım Jant',
          "PVC Ön ve Arka Kapı Eşikleri",
          "Hibrit Ön Silecekler",
          "Arkada Sportif Koruyucu Plakası",
          "Elektrikli, Katlanır ve Isıtmalı Dikiz Aynaları",
          "Solar Ön Cam",
        ],
      },
      {
        name: "İç Donanım",
        props: [
          "Derinlik ve Yükseklik Ayarlı Teleskopik Direksiyon",
          "Elektrikli Ön Camlar",
          "Elektrikli Arka Camlar",
          "Tek Dokunmalı Üçlü Sinyal",
          "Gümüş İç Kapı Kolları",
          "Otomatik Kararan Iç Dikiz Aynası",
          "12V Güç Soketi",
          "Deri Kaplama Koltuklar",
          "Deri Kaplama Direksiyon",
        ],
      },
      {
        name: "Bilgi Sistemi",
        props: [
          'Yol Bilgisayarı (3.5" Mono TFT-LCD Ekran)',
          "Direksiyondan Kumanda Sistemi",
          "Glonass DAB Uydu Konumlama",
          'Hayalet Kadran 10.25" Tam Renkli LCD',
        ],
      },
    ],
  },
];

export const mussoGrandPrices = [
  {
    model: "MUSSO GRAND D2.2 4X2 A/T PLATINUM (2024 GSR)",
    price: "1.498.894",
  },
  {
    model: "MUSSO GRAND D2.2 4X2 A/T PLATINUM PLUS - (2024 GSR)",
    price: "1.648.894",
  },
  {
    model: "MUSSO GRAND D2.2 4X2 A/T PLATINUM PLUS - (2025 GSR)",
    price: "1.793.894",
  },
  {
    model: "MUSSO GRAND D2.2 4X4 A/T PLATINUM PLUS - (2025 GSR)",
    price: "1.874.165",
  },
];

export const mussoGrandColors = [
  {
    name: "Beyaz",
    image: require("./arac_gorseller/musso_grand/musso_grand_beyaz.png"),
  },
  {
    name: "Mermer Gri",
    image: require("./arac_gorseller/musso_grand/musso_grand_mermer_gri.png"),
  },
  {
    name: "Amazon Yeşili",
    image: require("./arac_gorseller/musso_grand/musso_grand_amazon_yesili.png"),
  },
  {
    name: "Kum Bej",
    image: require("./arac_gorseller/musso_grand/musso_grand_kum_beji.png"),
  },
  {
    name: "Siyah",
    image: require("./arac_gorseller/musso_grand/musso_grand_siyah.png"),
  },
  {
    name: "Galaksi Gri",
    image: require("./arac_gorseller/musso_grand/musso_grand_galaksi_gri.png"),
  },
];

export const mussoGrandGallery = [
  require("./kgm-uygulama-dosyalar/gorsel/musso_grand_gallery1.jpg"),
  require("./kgm-uygulama-dosyalar/gorsel/musso_grand_gallery2.jpg"),
  require("./kgm-uygulama-dosyalar/gorsel/musso_grand_gallery3.jpg"),
  require("./kgm-uygulama-dosyalar/gorsel/musso_grand_gallery4.jpg"),
  require("./kgm-uygulama-dosyalar/gorsel/musso_grand_gallery5.jpg"),
  require("./kgm-uygulama-dosyalar/gorsel/musso_grand_gallery6.jpg"),
  require("./kgm-uygulama-dosyalar/gorsel/musso_grand_gallery7.jpg"),
  require("./kgm-uygulama-dosyalar/gorsel/musso_grand_gallery8.jpg"),
  require("./kgm-uygulama-dosyalar/gorsel/musso_grand_gallery9.jpg"),
  require("./kgm-uygulama-dosyalar/gorsel/musso_grand_gallery10.jpg"),
  require("./kgm-uygulama-dosyalar/gorsel/musso_grand_gallery11.jpg"),
  require("./kgm-uygulama-dosyalar/gorsel/musso_grand_gallery12.jpg"),
  require("./kgm-uygulama-dosyalar/gorsel/musso_grand_gallery13.jpg"),
  require("./kgm-uygulama-dosyalar/gorsel/musso_grand_gallery14.jpg"),
  require("./kgm-uygulama-dosyalar/gorsel/musso_grand_gallery15.jpg"),
  require("./kgm-uygulama-dosyalar/gorsel/torres_gallery.jpg"),
];

export const mussoGrandVideo = [
  {
    cover: require("./kgm-uygulama-dosyalar/gorsel/musso_grand_gallery10.jpg"),
    video: require("./kgm-uygulama-dosyalar/video/musso_grand_video.mp4"),
  },
];
