export const services = [
  {
    title: "YMY MALTEPE / ŞAHSUVAROĞLU",
    address: "Zümrütevler Mahallesi Acarlar Sokak No:3 Maltepe/İstanbul",
    phone: "+902164277373",
    is_service: true,
    is_dealer: true,
    id: 17,
  },
  {
    title: "YMY ANKARA",
    address: "İçi Blokları Mah. Mevlana Bulvarı No:162 Çankaya/Ankara",
    phone: "+903122292500",
    is_service: true,
    is_dealer: true,
    id: 18,
  },
  {
    title: "YMY ANTALYA",
    address: "Göksu Mah. Gazi Bulvarı No:621 Antalya",
    phone: "+902423395454",
    is_service: true,
    is_dealer: true,
    id: 19,
  },
  {
    title: "YMY BURSA",
    address: "İzmir Yolu Üzeri 8.Km No:279 Bursa",
    phone: "+902244431225",
    is_service: true,
    is_dealer: true,
    id: 20,
  },
  {
    title: "YMY ÇORLU",
    address: "Zafer Mah. Önerler Mevkii E-5 İstanbul Yolu Üzeri Çorlu/Tekirdağ",
    phone: "+902826854960",
    is_service: true,
    is_dealer: true,
    id: 21,
  },
  {
    title: "YMY ERZURUM",
    address: "Çağlayan Mah. Tortum Yolu Cad. No:134 Yakutiye/Erzurum",
    phone: "+904422424525",
    is_service: true,
    is_dealer: true,
    id: 22,
  },
  {
    title: "YMY İZMİR",
    address: "Akçay Caddesi No: 64/1 İzmir",
    phone: "+902322543425",
    is_service: true,
    is_dealer: true,
    id: 23,
  },
  {
    title: "YMY ADANA",
    address: "Kavaklı Mah.Turhan Cemal Beriker Bulvarı No:696/A Adana",
    phone: "+903224410070",
    is_service: true,
    is_dealer: true,
    id: 24,
  },
  {
    title: "YMY MERSİN",
    address: "Menderes Mah. Gazi Mustafa Kemal Bulvarı No: 789/A Mersin",
    phone: "+903243588200",
    is_service: true,
    is_dealer: true,
    id: 25,
  },
  {
    title: "YMY TRABZON",
    address: "Adnan Kahveci Bulvarı No:67 Söğütlü/Trabzon",
    phone: "+904622486565",
    is_service: true,
    is_dealer: true,
    id: 26,
  },
  {
    title: "YMY TUZLA",
    address: "Aydıntepe Mah. E-5 Karayolu No:4 Tuzla/İstanbul",
    phone: "+902163927979",
    is_service: true,
    is_dealer: true,
    id: 27,
  },
  {
    title: "YMY YENİBOSNA",
    address: "Çınar Caddesi No:34 Yenibosna/İstanbul",
    phone: "+902124528000",
    is_service: true,
    is_dealer: true,
    id: 28,
  },
  {
    title: "TUNCERHAN OTOMOTİV",
    address: "Gümüşcay Mah Adnan Menderes Blv No 33/c Merkezefendi/Denizli",
    phone: "+902582643994",
    is_service: true,
    is_dealer: true,
    id: 31,
  },
  {
    title: "NEZİROĞLU OTOMOTİV",
    address: "Eskişehir Yolu No:108/B Söğütözü / Ankara",
    phone: "+903122845252",
    is_service: false,
    is_dealer: true,
    id: 32,
  },
  {
    title: "ALKANLAR OTOMOTİV",
    address:
      "Konacık Mahallesi, Konacık Sanayi Sitesi D Blok No:8 Bodrum/Muğla",
    phone: "+902523638279",
    is_service: true,
    is_dealer: false,
    id: 33,
  },
  {
    title: "ÇELİK OTOMOTİV",
    address:
      "Cennetayağı mahallesi Alpaslan Türkeş bulvarı. No11/1 Edremit Balıkesir",
    phone: "(0266) 372 24 24",
    is_service: true,
    is_dealer: true,
    id: 34,
  },
  {
    title: "OTOSTORE OTOMOTİV",
    address: "Barış Mah. 1019 Sok. No:50 Kayapınar/Diyarbakır",
    phone: "(0412) 502 60 97",
    is_service: true,
    is_dealer: true,
    id: 35,
  },
  {
    title: "SUR OTOMOTİV",
    address: "Kervansaray Mah. 1973. Sk. No:2/4 Merkez/KIRŞEHİR",
    phone: "+903862527966",
    is_service: false,
    is_dealer: true,
    id: 36,
  },
  {
    title: "GRUP İLBEY OTOMOTİV",
    address: "Yenişehir Mh. Ravza Cd. 1931 Sk. İlhan Apt. 47200 Artuklu/Mardin",
    phone: "(0482) 212 49 00",
    is_service: true,
    is_dealer: false,
    id: 37,
  },
  {
    title: "ANIL OTOMOTİV",
    address:
      "Mustafa Kemal Mah. İbrahim Karaoğlanoğlu Cad. No.80/A İskenderun / Hatay",
    phone: "+903266187700",
    is_service: true,
    is_dealer: true,
    id: 43,
  },
  {
    title: "B MOTORS SİVAS",
    address: "Yeşilyurt Mah. Sultanşehir Blv. No 88/B  Merkez / SİVAS",
    phone: "0346 226 30 58",
    is_service: false,
    is_dealer: true,
    id: 44,
  },
  {
    title: "AHİ GROUP OTOMOTİV",
    address: "Gülalibey Mah. 967 Sk. No: 28 Merkez / Erzincan",
    phone: "(0446) 214 75 88",
    is_service: true,
    is_dealer: false,
    id: 45,
  },
  {
    title: "KONYA PRATİK OTOMOTİV",
    address:
      "Kottim İş Merkezi Fevzi Çakmak Mahallesi Çelik Caddesi No:8 Karatay/ KONYA",
    phone: "(0332) 238 63 26",
    is_service: true,
    is_dealer: false,
    id: 48,
  },
  {
    title: "KONYA TAMİR BAKIM SERVİSİ (AHTAP OTO)",
    address:
      "Musalla Bağları Mahallesi Gürsesler Sk. Sefer A.Ş. Sitesi N:2 Selçuklu/Konya",
    phone: "(0332) 244 10 10",
    is_service: true,
    is_dealer: false,
    id: 50,
  },
  {
    title: "ADAŞEN OTOMOTİV",
    address: "Adnan Menderes Cad. No: 143 Adapazarı / SAKARYA",
    phone: "(0264) 359 54 54",
    is_service: true,
    is_dealer: true,
    id: 54,
  },
  {
    title: "AYHAN OTOMOTİV",
    address: "1.Sanayi Sitesi B Blok No: 9-10 Zonguldak",
    phone: "+903723161896",
    is_service: true,
    is_dealer: false,
    id: 55,
  },
  {
    title: "AYIK OTOMOTİV",
    address:
      "Mehmet Akif Ersoy Mh. Yeni Sanayi Girişi Halifelik Cad. No:1-2 Sivas",
    phone: "+903462151208",
    is_service: true,
    is_dealer: false,
    id: 56,
  },
  {
    title: "ÇETİN OTOMOTİV",
    address: "Taşyaka Mah. Yeni San. Sitesi 254. Sok. No:27 Muğla",
    phone: "+902526145488",
    is_service: true,
    is_dealer: false,
    id: 57,
  },
  {
    title: "GANİ KARDEŞLER",
    address: "Gülabi Bey Mah. 967.Sok. No:28-32 Bolu",
    phone: "+903742158455",
    is_service: true,
    is_dealer: false,
    id: 58,
  },
  {
    title: "GÜÇLÜ OTOMOTİV",
    address: "Ataşehir Mah. Malatya Cad. Cezaevi Sok. No: 289 Elazığ",
    phone: "+904242471801",
    is_service: true,
    is_dealer: false,
    id: 59,
  },
  {
    title: "GÜRCAN OTOMOTİV",
    address: "Atatürk Oto Sanayi Sitesi 1. Kısım A Blok No:78 Maslak/İstanbul",
    phone: "+902123462608",
    is_service: true,
    is_dealer: false,
    id: 60,
  },
  {
    title: "KESKİN KARDEŞLER",
    address:
      "Toybelen Mah. Anadolu Bulvarı No:175 İç Kapı No: Z1 İlkadım/Samsun",
    phone: "+903622665583",
    is_service: true,
    is_dealer: false,
    id: 61,
  },
  {
    title: "OTOFORS OTOMOTİV",
    address: "Sümer Mah. 53. Sok. No:29 Merkezefendi/Denizli",
    phone: "+902582666159",
    is_service: true,
    is_dealer: false,
    id: 62,
  },
  {
    title: "ŞAHİN OTOMOTİV",
    address: "2.Küçük Sanayi Sitesi 6.Ada 4.Blok No: 5 Afyon",
    phone: "+902722234545",
    is_service: true,
    is_dealer: false,
    id: 63,
  },
  {
    title: "TÜREL OTOMOTİV",
    address: "Yeni Sanayi Sitesi 3.Cad 84.Sokak Kayseri",
    phone: "+903523325848",
    is_service: true,
    is_dealer: false,
    id: 64,
  },
  {
    title: "UZMANN OTOMOTİV",
    address: "Kestel Mah. Semt Sahil Cad. 23 Z01 Alanya/Antalya",
    phone: "(0242) 515 16 18",
    is_service: true,
    is_dealer: false,
    id: 65,
  },
  {
    title: "ALN OTOMOTİV",
    address: "Sarayatik, Cahit Dalokay Blv. No:2, 23100 Elazığ Merkez/Elazığ",
    phone: "+904242185050",
    is_service: true,
    is_dealer: true,
    id: 67,
  },
  {
    title: "ULAK OTOMOTIV",
    address: "SÜPHAN MAH. IPEKYOLU BLV. NO: 351 EDREMIT/ VAN",
    phone: "(0432) 217 03 03",
    is_service: true,
    is_dealer: true,
    id: 69,
  },
  {
    title: "KARAKUCAK OTOMATIV",
    address: "ATAKENT MAH. 6052 SK. NO: 1 IÇ KAPI NO: 1 KARAKÖPRÜ / ŞANLIURFA",
    phone: "0850 281 6311",
    is_service: false,
    is_dealer: true,
    id: 72,
  },
  {
    title: "KARAKUCAK OTOMATIV",
    address: "KADIKENDİ MAH. 8728 CAD. NO: 20E EYYÜBİYE ŞANLIURFA",
    phone: "0850 281 6311",
    is_service: true,
    is_dealer: false,
    id: 73,
  },
  {
    title: "ALN OTOMOTİV KAYSERİ",
    address:
      "Osman Kavuncu Mah.Osman Kavuncu Bulvarı No:197/A  Melikgazi KAYSERİ",
    phone: "+903523302023",
    is_service: false,
    is_dealer: true,
    id: 76,
  },
  {
    title: "ALN OTOMOTİV KAYSERİ SERVİS",
    address: "Osman Kavuncu Mah. Kevser Cad. No:93D  Melikgazi KAYSERİ",
    phone: "+903523302023",
    is_service: true,
    is_dealer: false,
    id: 77,
  },
  {
    title: "DURMAZ INVEST",
    address: "Fabrikalar Mah. Namık Kemal Bulvarı No:51A Kepez/ANTALYA",
    phone: "+902425040758",
    is_service: false,
    is_dealer: true,
    id: 78,
  },
  {
    title: "OTOSTORE OTOMOTİV",
    address:
      "Turgut Özal Mahallesi Mardin Caddesi Mova AVM No:416 İç Kapı No:28 Kızıltepe/Mardin",
    phone: "+904826060689",
    is_service: false,
    is_dealer: true,
    id: 79,
  },
  {
    title: "AKORT OTOMOTİV",
    address: "Sanayi Mah. 60704 Cad. No:25A Şehitkamil / Gaziantep",
    phone: "+905382132744",
    is_service: true,
    is_dealer: false,
    id: 80,
  },
  {
    title: "ÇİFTKURTLAR OTOMOTİV",
    address:
      "Maslak Mah. AOS 38. Sok. Çiftkurtlar Plaza Blok No:351 İç Kapı No:1 Sarıyer/İSTANBUL",
    phone: "+902123462222",
    is_service: false,
    is_dealer: true,
    id: 81,
  },
  {
    title: "ASAL OTOMOTİV",
    address: "Ayazağa Mah. Cendere Sok. No:5 Sarıyer / İSTANBUL",
    phone: "+902122898800",
    is_service: true,
    is_dealer: true,
    id: 82,
  },
  {
    title: "UYARASLAN OTOMOTİV",
    address:
      "Sancak Mah. Dr. Sadık Ahmet Cad. No:21 Uyaraslan Plaza Selçuklu/Konya",
    phone: "(0332) 255 33 99",
    is_service: true,
    is_dealer: true,
    id: 83,
  },
  {
    title: "ÖZPAM OTOMOTİV",
    address: "Konacık Mah. Atatürk Bulvarı No:245/3 Bodrum/Muğla",
    phone: "(0252) 313 22 66",
    is_service: true,
    is_dealer: true,
    id: 84,
  },
  {
    title: "DMR OTOMOTİV",
    address: "Kirazlık Mah. Atatuörk Bulvarı No: 66 Tekkekoöy / Samsun",
    phone: "+903622705500",
    is_service: true,
    is_dealer: true,
    id: 85,
  },
  {
    title: "ÜMİT ÜNL OTOMOTİV",
    address: "Alata Mah. Osman Çavuş Sk. No:60 Erdemli / Mersin",
    phone: "(0324) 515 96 40",
    is_service: false,
    is_dealer: true,
    id: 86,
  },
  {
    title: "DURMAZ INVEST",
    address:
      "Kızlar Pınarı Mah. Çekiçoğlu sk. Gülcihan Apt. No:10 Alanya / Antalya",
    phone: "(0242) 504 55 07",
    is_service: false,
    is_dealer: true,
    id: 87,
  },
  {
    title: "YMY KUMLUCA",
    address: "GÖKSU MAH AHMET ALİAĞA BULVARI 224 BB KUMLUCA ANTALYA",
    phone: "+905326776590",
    is_service: false,
    is_dealer: true,
    id: 89,
  },
  {
    title: "METELER OTOMOTİV",
    address: "İslam Paşa Mah.Hopa Cad. NO:470  MERKEZ / RİZE",
    phone: "+904642133839",
    is_service: true,
    is_dealer: true,
    id: 90,
  },
  {
    title: "B MOTORS BURSA",
    address: "Panayır Mah. İstanbul Cad. No:379 Osmangazi / BURSA",
    phone: "+902242235858",
    is_service: false,
    is_dealer: true,
    id: 91,
  },
  {
    title: "SİSTEM OTOMOTİV",
    address: "Vezirçiftliği Mah. D130 Karayolu Cad. No:116 Başiskele / Kocaeli",
    phone: "+902622331010",
    is_service: true,
    is_dealer: true,
    id: 92,
  },
];
