export const torresModels = [
  {
    name: "Torres 4x2",
    slug: "torres_4x2",
    image: require("./kgm-uygulama-dosyalar/torres_mavi.png"),
    desc_item: ["Otomatik", "Benzinli", "4x2"],
    desc: "₺2.198.700'den başlayan fiyatlarla",
    technic_properties: [
      {
        name: "Genel Bakış",
        props: [
          {
            name: "Kapı Sayısı",
            value: "5 Kapı",
          },
          {
            name: "Azami Sürat",
            value: "191 km/saat",
          },
          {
            name: "Silindir Sayısı",
            value: "4 Silindir",
          },
          {
            name: "Vites Sayısı",
            value: "6 Vites",
          },
        ],
      },
      {
        name: "Motor ve Performans",
        props: [
          {
            name: "Motor Gücü",
            value: "163 HP",
          },
          {
            name: "Motor Hacmi",
            value: "1497 cc",
          },
          {
            name: "Maksimum Tork",
            value: "280 Nm (1500-4000 d/dk)",
          },
          {
            name: "Maksimum Devir",
            value: "5000-5500 rpm",
          },
        ],
      },
      {
        name: "Yakıt Tüketimi",
        props: [
          {
            name: "Ortalama Yakıt Tüketimi",
            value: "8.5 L",
          },
          {
            name: "Yakıt Deposu",
            value: "50 L",
          },
        ],
      },
      {
        name: "Boyutlar",
        props: [
          {
            name: "Koltuk Sayısı",
            value: "5 Koltuk",
          },
          {
            name: "Uzunluk",
            value: "4700 mm",
          },
          {
            name: "Genişlik",
            value: "1890 mm",
          },
          {
            name: "Yükseklik",
            value: "1710/1720 (Port Bagajlı) mm",
          },
          {
            name: "Net Ağırlık",
            value: "1603 kg",
          },
          {
            name: "Bagaj Hacmi",
            value: "839 lt",
          },
          {
            name: "Lastik Ölçüleri",
            value: '235/55R 18"',
          },
        ],
      },
    ],
    hardware_properties: [
      {
        name: "Güvenlik",
        props: [
          "ARP (Aktif Devrilme Önleyici)",
          "HSA (Yokuş Kalkış Sistemi)",
          "HDC (Yokuş İniş Kontrolü)",
          "TPMS (Lastik Basıncı İzleme Sistemi)",
          "Ön Emniyet Kemeri Yük Sınırlama Düzeneği ve Kilitleme Dilli Ön Gergiler",
          "Hızı Algılayan Otomatik Kapı Kilitleri",
          "Hıza Duyarlı Emniyet Kemeri Uyarısı",
          "AEBS (Bağımsız Acil Fren Sistemi)",
          "LDW ( Şeritten Çıkış Uyarısı)",
          "LKA ( Şerit Koruma Asistanı)",
          "HBA (Uzun Far Asistanı)",
          "SDA (Emniyetli Mesafe Uyarısı)",
          "DAA (Sürücü Yorgunluk Uyarısı)",
          "FVSA (Öndeki Araç İçin Hareket Uyarısı)",
          "Takviyeli Monoblok Gövde Yapısı",
          "Yan Darbelere Karşı Kapı Darbe Kirişleri",
          "Alarm",
          "ESS (Acil Durum Arka Sinyal Sistemi)",
          "ESP (Elektronik Stabilite Programı)",
          "ABS (Kilitlenme Karşıtı Fren Sistemi)",
          "TCS (Çekiş Kontrol Sistemi)",
          "HBA (Hidrolik Fren Asistanı)",
          "Immobilizer",
          "Sürücü ve Yolcu Ön Hava Yastıkları",
          "Sürücü ve Yolcu Yan Hava Yastıkları",
          "Sürücü Perde Hava Yastığı",
          "Ön Yolcu Perde Hava Yastığı",
          "Ön Yolcu Hava Yastığı Kapama Düğmesi",
          "Önde Hava Soğutmalı Disk Frenler",
          "Arkada Disk Frenler",
          "Yükseklik Ayarlı Ön Emniyet Kemerleri",
          "Arka Koltuklarda Üç Noktadan Bağlantılı Emniyet Kemer Sistemi",
          "Çocuk Güvenlik Kilidi",
          "Hıza Duyarlı Kapı Kilidi",
          "Sürücü Diz Hava Yastığı",
          "Isofıx Çocuk Koltuğu Bağlantısı",
          "FTCS-Çekiş Kontrol Sistemi",
          "FCW-Ön Çarpışma Uyarısı",
          "RCTA-Arka Çapraz Trafik Uyarısı",
          "Arka Yolcu Perde Hava Yastıkları",
          "Park Asistanı Sistemi",
          "Yüksek Gergili Çelik Yapı",
          "Darbe Emici Özellikli Kapı Kirişleri",
          "BSD-Kör Nokta Uyarı Sistemi",
          "İlk Yardım Kiti",
        ],
      },
      {
        name: "Multimedia",
        props: [
          "Araç Bağlantısı (Apple Carplay/Google Android Auto)",
          "6 Adet Hoparlör",
          "Bluetooth Bağlantı",
          "USB Bağlantısı",
        ],
      },
      {
        name: "Konfor",
        props: [
          "Cruise Control (Hız Sabitleme Sistemi)",
          "Lastik Tamir Kiti",
          "Anahtarsız Giriş ve Çalıştırma (Start & Stop)",
          "Yeni Tip Çok Fonksiyonlu Anahtar (Smart-Key)",
          "8 Yönlü Elektrikli Koltuk",
          "60/40 Katlanabilir ve Yatırılabilir 2.Sıra Koltuklar",
          "Işıklı Makyaj Aynası",
          "Bardak Tutuculu Arka Kol Dayama",
          "Isıtmalı Arka Koltuklar",
          "Çift Bölgeli İyonizerli Otomatik Klima",
          "Arka Koltuk Klima Ünitesi-Manuel",
          "Kabin İçi Hava Kalite Kontrol Sistemi",
          "Elektronik Far Yükseklik Ayarı",
          "Yağmur Sensörü",
          "Isıtmalı ve Soğutmalı Ön Koltuklar",
          "Kablosuz Şarj",
          "Smart Key (Akıllı Anahtar-Anahtarsız Giriş/Çalıştırma/Kilitleme)",
          "Sürüş Modları Sistemi (Normal/Kış/Spor)",
          "Elektronik Park Freni (Otomatik Tutmalı)",
          "EPS (Elektrik Destekli Direksiyon)",
          "Çok Bağlantılı Spiral Arka Süspansiyon",
          "Yükseklik Ayarlı Sürücü Koltuğu",
          "Isıtmalı Ön Koltuklar",
          "Bardak Tutucu (Ön ve Arka)",
          "McPherson Spiral Ön Süspansiyon Sistemi",
        ],
      },
      {
        name: "Dış Donanım",
        props: [
          "5 Noktadan Bağlantılı Bağımsız Arka Süspansiyon",
          "Geri Görüş Kamerası ve Park Kılavuz Çizgileri",
          "Arka Sis Farları",
          "Ön Sis Farları",
          "Dış Aynalarda Led Sinyal Lambaları",
          "LED Arka Stop",
          "Köpekbalığı Anten",
          "Ön ve Arka Park Sensörü",
          "Karartılmış Arka Camlar",
          "Elektrikli Güvenlikli Sürücü Camı",
          '18" Alüminyum Alaşım Jant',
          "Gövde Rengi Kapı Kolları",
          "Ön Kapı Aydınlatma Lambası",
          "Elektrikli, Katlanır ve Isıtmalı Dikiz Aynaları",
          "Arkada Sportif Koruyucu Plakası",
          "Tavan Çıtaları",
          "Renkli Yan Camlar",
          "Ses Yalıtımlı Renkli Ön Cam",
          "Siyah Hava Giriş Izgarası",
          "Sesi Azaltan Akustik Motor Kapağı",
          "Aralıklı Arka Cam Sileceği",
          "Görsel VIN (Şasi Numarası)",
          "LED Işıklı Gündüz Farları",
          "Sunroof",
        ],
      },
      {
        name: "İç Donanım",
        props: [
          "Işığa Duyarlı Elektrokrom İç Dikiz Aynası",
          "Manuel Eğim Kontrollü Teleskopik Direksiyon",
          "Ön Konsol Arkasında 12V Güç Çıkışı ve USB Şarj",
          "Elektrikli Arka Camlar",
          "LED Kabin İçi Aydınlatma",
          "12V Güç Soketi",
          "Elektrikli Ön Camlar",
          "Deri Kaplama Direksiyon",
          "Gümüş İç Kapı Kolları",
        ],
      },
    ],
  },
  {
    name: "Torres 4x4",
    slug: "torres_4x4",
    image: require("./kgm-uygulama-dosyalar/gorsel/torres4.png"),
    desc_item: ["Otomatik", "Benzinli", "4x4"],
    desc: "₺2.418.700'den başlayan fiyatlarla",
    technic_properties: [
      {
        name: "Genel Bakış",
        props: [
          {
            name: "Kapı Sayısı",
            value: "5 Kapı",
          },
          {
            name: "Azami Sürat",
            value: "191 km/saat",
          },
          {
            name: "Silindir Sayısı",
            value: "4 Silindir",
          },
          {
            name: "Vites Sayısı",
            value: "6 Vites",
          },
        ],
      },
      {
        name: "Motor ve Performans",
        props: [
          {
            name: "Motor Gücü",
            value: "163 HP",
          },
          {
            name: "Motor Hacmi",
            value: "1497 cc",
          },
          {
            name: "Maksimum Tork",
            value: "280 Nm (1500-4000 d/dk)",
          },
          {
            name: "Maksimum Devir",
            value: "5000-5500 rpm",
          },
        ],
      },
      {
        name: "Yakıt Tüketimi",
        props: [
          {
            name: "Ortalama Yakıt Tüketimi",
            value: "9.08 L",
          },
          {
            name: "Yakıt Deposu",
            value: "50 L",
          },
        ],
      },
      {
        name: "Boyutlar",
        props: [
          {
            name: "Koltuk Sayısı",
            value: "5 Koltuk",
          },
          {
            name: "Uzunluk",
            value: "4700 mm",
          },
          {
            name: "Genişlik",
            value: "1890 mm",
          },
          {
            name: "Yükseklik",
            value: "1710/1720 (Port Bagajlı) mm",
          },
          {
            name: "Net Ağırlık",
            value: "1693 kg",
          },
          {
            name: "Bagaj Hacmi",
            value: "839 lt",
          },
          {
            name: "Lastik Ölçüleri",
            value: '235/55R 20"',
          },
        ],
      },
    ],
    hardware_properties: [
      {
        name: "Güvenlik",
        props: [
          "ARP (Aktif Devrilme Önleyici)",
          "HSA (Yokuş Kalkış Sistemi)",
          "HDC (Yokuş İniş Kontrolü)",
          "TPMS (Lastik Basıncı İzleme Sistemi)",
          "Ön Emniyet Kemeri Yük Sınırlama Düzeneği ve Kilitleme Dilli Ön Gergiler",
          "Hızı Algılayan Otomatik Kapı Kilitleri",
          "Hıza Duyarlı Emniyet Kemeri Uyarısı",
          "AEBS (Bağımsız Acil Fren Sistemi)",
          "LDW ( Şeritten Çıkış Uyarısı)",
          "LKA ( Şerit Koruma Asistanı)",
          "HBA (Uzun Far Asistanı)",
          "SDA (Emniyetli Mesafe Uyarısı)",
          "DAA (Sürücü Yorgunluk Uyarısı)",
          "FVSA (Öndeki Araç İçin Hareket Uyarısı)",
          "Takviyeli Monoblok Gövde Yapısı",
          "Yan Darbelere Karşı Kapı Darbe Kirişleri",
          "Alarm",
          "ESS (Acil Durum Arka Sinyal Sistemi)",
          "ESP (Elektronik Stabilite Programı)",
          "ABS (Kilitlenme Karşıtı Fren Sistemi)",
          "TCS (Çekiş Kontrol Sistemi)",
          "HBA (Hidrolik Fren Asistanı)",
          "Immobilizer",
          "Sürücü ve Yolcu Ön Hava Yastıkları",
          "Sürücü ve Yolcu Yan Hava Yastıkları",
          "Sürücü Perde Hava Yastığı",
          "Ön Yolcu Perde Hava Yastığı",
          "Ön Yolcu Hava Yastığı Kapama Düğmesi",
          "Önde Hava Soğutmalı Disk Frenler",
          "Arkada Disk Frenler",
          "Yükseklik Ayarlı Ön Emniyet Kemerleri",
          "Arka Koltuklarda Üç Noktadan Bağlantılı Emniyet Kemer Sistemi",
          "Çocuk Güvenlik Kilidi",
          "Hıza Duyarlı Kapı Kilidi",
          "Sürücü Diz Hava Yastığı",
          "Isofıx Çocuk Koltuğu Bağlantısı",
          "FTCS-Çekiş Kontrol Sistemi",
          "FCW-Ön Çarpışma Uyarısı",
          "RCTA-Arka Çapraz Trafik Uyarısı",
          "Arka Yolcu Perde Hava Yastıkları",
          "Park Asistanı Sistemi",
          "Yüksek Gergili Çelik Yapı",
          "Darbe Emici Özellikli Kapı Kirişleri",
          "BSD-Kör Nokta Uyarı Sistemi",
          "İlk Yardım Kiti",
        ],
      },
      {
        name: "Multimedia",
        props: [
          "Araç Bağlantısı (Apple Carplay/Google Android Auto)",
          "6 Adet Hoparlör",
          "Bluetooth Bağlantı",
          "USB Bağlantısı",
        ],
      },
      {
        name: "Konfor",
        props: [
          "Cruise Control (Hız Sabitleme Sistemi)",
          "Lastik Tamir Kiti",
          "Anahtarsız Giriş ve Çalıştırma (Start & Stop)",
          "Yeni Tip Çok Fonksiyonlu Anahtar (Smart-Key)",
          "8 Yönlü Elektrikli Koltuk",
          "60/40 Katlanabilir ve Yatırılabilir 2.Sıra Koltuklar",
          "Işıklı Makyaj Aynası",
          "Bardak Tutuculu Arka Kol Dayama",
          "Isıtmalı Arka Koltuklar",
          "Çift Bölgeli İyonizerli Otomatik Klima",
          "Arka Koltuk Klima Ünitesi-Manuel",
          "Kabin İçi Hava Kalite Kontrol Sistemi",
          "Elektronik Far Yükseklik Ayarı",
          "Yağmur Sensörü",
          "Isıtmalı ve Soğutmalı Ön Koltuklar",
          "Kablosuz Şarj",
          "Smart Key (Akıllı Anahtar-Anahtarsız Giriş/Çalıştırma/Kilitleme)",
          "Sürüş Modları Sistemi (Normal/Kış/Spor)",
          "Elektronik Park Freni (Otomatik Tutmalı)",
          "EPS (Elektrik Destekli Direksiyon)",
          "Çok Bağlantılı Spiral Arka Süspansiyon",
          "Yükseklik Ayarlı Sürücü Koltuğu",
          "Isıtmalı Ön Koltuklar",
          "Bardak Tutucu (Ön ve Arka)",
          "McPherson Spiral Ön Süspansiyon Sistemi",
        ],
      },
      {
        name: "Dış Donanım",
        props: [
          "5 Noktadan Bağlantılı Bağımsız Arka Süspansiyon",
          "Geri Görüş Kamerası ve Park Kılavuz Çizgileri",
          "Arka Sis Farları",
          "Ön Sis Farları",
          "Dış Aynalarda Led Sinyal Lambaları",
          "LED Arka Stop",
          "Köpekbalığı Anten",
          "Ön ve Arka Park Sensörü",
          "Elektrikli Bagaj Kapağı",
          "Karartılmış Arka Camlar",
          "Elektrikli Güvenlikli Sürücü Camı",
          '20" Alüminyum Alaşım Jant',
          "Gövde Rengi Kapı Kolları",
          "Ön Kapı Aydınlatma Lambası",
          "Elektrikli, Katlanır ve Isıtmalı Dikiz Aynaları",
          "Arkada Sportif Koruyucu Plakası",
          "Tavan Çıtaları",
          "Renkli Yan Camlar",
          "Ses Yalıtımlı Renkli Ön Cam",
          "Siyah Hava Giriş Izgarası",
          "Sesi Azaltan Akustik Motor Kapağı",
          "Aralıklı Arka Cam Sileceği",
          "Görsel VIN (Şasi Numarası)",
          "LED Işıklı Gündüz Farları",
          "Sunroof",
        ],
      },
      {
        name: "İç Donanım",
        props: [
          "Işığa Duyarlı Elektrokrom İç Dikiz Aynası",
          "Manuel Eğim Kontrollü Teleskopik Direksiyon",
          "Ön Konsol Arkasında 12V Güç Çıkışı ve USB Şarj",
          "Elektrikli Arka Camlar",
          "LED Kabin İçi Aydınlatma",
          "12V Güç Soketi",
          "Elektrikli Ön Camlar",
          "Deri Kaplama Direksiyon",
          "Gümüş İç Kapı Kolları",
        ],
      },
    ],
  },
];

export const torresPrices = [
  {
    model: "4x2 1.5 GDI Turbo (2025 Model)",
    price: "2.198.700",
  },
   {
    model: "4x4 1.5 GDI Turbo (2025 Model)",
    price: "2.418.700",
  },
];

export const torresColors = [
  {
    name: "Amazon Yeşili",
    image: require("./arac_gorseller/torres/torres_amazon_yesili.png"),
  },
  {
    name: "Dandy Mavi",
    image: require("./arac_gorseller/torres/torres_dandy_mavi.png"),
  },
  {
    name: "Grand Beyaz",
    image: require("./arac_gorseller/torres/torres_grand_beyaz.png"),
  },
  {
    name: "Kiraz Kırmızı",
    image: require("./arac_gorseller/torres/torres_kiraz_kırmızı.png"),
  },
  {
    name: "Metal Rengi",
    image: require("./arac_gorseller/torres/torres_metal_rengi.png"),
  },
  {
    name: "Platinum Gri",
    image: require("./arac_gorseller/torres/torres_platinum_gri.png"),
  },
  {
    name: "Uzay Siyah",
    image: require("./arac_gorseller/torres/torres_uzay_siyahi.png"),
  },
];

export const torresGallery = [
  require("./kgm-uygulama-dosyalar/gorsel/torres_gallery.jpg"),
  require("./kgm-uygulama-dosyalar/gorsel/torres_gallery2.jpg"),
  require("./kgm-uygulama-dosyalar/gorsel/torres_gallery3.jpg"),
  require("./kgm-uygulama-dosyalar/gorsel/torres_gallery4.jpg"),
  require("./kgm-uygulama-dosyalar/gorsel/torres_gallery5.jpg"),
  require("./kgm-uygulama-dosyalar/gorsel/torres_gallery6.jpg"),
  require("./kgm-uygulama-dosyalar/gorsel/torres_gallery7.jpg"),
  require("./kgm-uygulama-dosyalar/gorsel/torres_gallery8.jpg"),
  require("./kgm-uygulama-dosyalar/gorsel/torres_gallery9.jpg"),
  require("./kgm-uygulama-dosyalar/gorsel/torres_gallery10.jpg"),
  require("./kgm-uygulama-dosyalar/gorsel/torres_gallery11.jpg"),
  require("./kgm-uygulama-dosyalar/gorsel/torres_gallery12.jpg"),
  require("./kgm-uygulama-dosyalar/gorsel/torres_gallery13.jpg"),
  require("./kgm-uygulama-dosyalar/gorsel/torres_gallery14.jpg"),
  require("./kgm-uygulama-dosyalar/gorsel/torres_gallery15.jpg"),
  require("./kgm-uygulama-dosyalar/gorsel/torres_gallery16.jpg"),
];

export const torresVideo = [
  {
    cover: require("./kgm-uygulama-dosyalar/gorsel/torres_video_cover.png"),
    video: require("./kgm-uygulama-dosyalar/video/torres_video.mp4"),
  },
];
